# Generated by Django 3.1 on 2020-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boast', models.BooleanField()),
                ('content', models.CharField(max_length=250)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
