# Generated by Django 3.1 on 2020-08-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_boast',
            field=models.BooleanField(choices=[('Boast', True), ('Roast', False)]),
        ),
    ]
