# Generated by Django 3.1 on 2020-08-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0002_auto_20200820_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_boast',
            field=models.BooleanField(choices=[(True, 'Boast'), (False, 'Roast')]),
        ),
    ]
